/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parques_juego;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import logica_parques.Repositorio;
import static parques_juego.Historial.table_model_personas;
import static parques_juego.Parques.tablero;

/**
 *
 * @author Pavilion 15
 */
public class MejorPuntaje extends javax.swing.JFrame {

    /**
     * Creates new form MejorPuntaje
     */
    public MejorPuntaje() {
        initComponents();
        configComponents();
        configComponents1();
        configComponents2();
        configComponents3();
    }

    public void configComponents() {
        ImageIcon fondo = new ImageIcon(getClass().getResource("/images/wallpaper.jpg"));
        ImageIcon icon = new ImageIcon(fondo.getImage().getScaledInstance(labelfondo.getWidth(), labelfondo.getHeight(), Image.SCALE_DEFAULT));
        labelfondo.setIcon(icon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        labelfondo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mejores Puntajes");
        setBackground(new java.awt.Color(153, 255, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(470, 540));
        setMinimumSize(new java.awt.Dimension(470, 540));
        setPreferredSize(new java.awt.Dimension(470, 540));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 50, 420, 101);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mejores puntajes infantil");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 20, 150, 14);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 210, 415, 103);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mejores puntajes mayores");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 330, 200, 14);

        jLabel2.setBackground(new java.awt.Color(102, 102, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mejores puntajes juvenil");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 170, 170, 14);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 370, 420, 111);

        labelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallpaper.jpg"))); // NOI18N
        labelfondo.setMaximumSize(new java.awt.Dimension(450, 540));
        labelfondo.setMinimumSize(new java.awt.Dimension(450, 540));
        labelfondo.setPreferredSize(new java.awt.Dimension(450, 540));
        getContentPane().add(labelfondo);
        labelfondo.setBounds(4, 0, 450, 520);

        jPanel1.setMaximumSize(new java.awt.Dimension(450, 520));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 450, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public static DefaultTableModel table_model_personas;
    public static DefaultTableModel table_model_personas1;
    public static DefaultTableModel table_model_personas2;

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MejorPuntaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MejorPuntaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MejorPuntaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MejorPuntaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MejorPuntaje().setVisible(true);
            }
        });
    }

    public void setTableModel(DefaultTableModel table_model_personas) {
        this.table_model_personas = table_model_personas;
    }

    public void setTableModel1(DefaultTableModel table_model_personas1) {
        this.table_model_personas1 = table_model_personas1;
    }

    public void setTableModel2(DefaultTableModel table_model_personas2) {
        this.table_model_personas2 = table_model_personas2;
    }

    public void refreshTableModel() {
        ArrayList<HistorialJuegos> lista_personas = Repositorio.obtenerTodos();
        while (table_model_personas.getRowCount() > 0) {
            table_model_personas.removeRow(0);
        }

        for (HistorialJuegos p : lista_personas) {

            String[] data = {Integer.toString(p.getCedula()), Integer.toString(p.getPuntaje())};
            table_model_personas.addRow(data);
        }
    }

    public void refreshTableModel1() {
        ArrayList<HistorialJuegos> lista_personas1 = Repositorio.obtenerTodos();
        while (table_model_personas1.getRowCount() > 0) {
            table_model_personas1.removeRow(0);
        }

        for (HistorialJuegos p : lista_personas1) {

            String[] data = {Integer.toString(p.getCedula()), Integer.toString(p.getPuntaje())};
            table_model_personas1.addRow(data);
        }
    }
    public void refreshTableModel2() {
        ArrayList<HistorialJuegos> lista_personas2 = Repositorio.obtenerTodos();
        while (table_model_personas2.getRowCount() > 0) {
            table_model_personas2.removeRow(0);
        }

        for (HistorialJuegos p : lista_personas2) {

            String[] data = {Integer.toString(p.getCedula()), Integer.toString(p.getPuntaje())};
            table_model_personas2.addRow(data);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel labelfondo;
    // End of variables declaration//GEN-END:variables
private void configComponents1() {
        DefaultTableModel table_model_personas = new DefaultTableModel();

        table_model_personas.addColumn("Cedula");
        table_model_personas.addColumn("Puntaje");
        table_model_personas.addColumn("Edad");

        jTable1.setModel(table_model_personas);

        setTableModel(table_model_personas);
        refreshTableModel();
    }

    private void configComponents2() {
        DefaultTableModel table_model_personas1 = new DefaultTableModel();

        table_model_personas1.addColumn("Cedula");
        table_model_personas1.addColumn("Puntaje");
        table_model_personas1.addColumn("Edad");

        jTable2.setModel(table_model_personas1);

        setTableModel1(table_model_personas1);
        refreshTableModel1();
    }

    private void configComponents3() {
        DefaultTableModel table_model_personas2 = new DefaultTableModel();

        table_model_personas2.addColumn("Cedula");
        table_model_personas2.addColumn("Puntaje");
        table_model_personas2.addColumn("Edad");

        jTable3.setModel(table_model_personas2);

        setTableModel2(table_model_personas2);
        refreshTableModel2();
    }
}
