/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parques_juego;

import java.awt.Image;
import javax.swing.ImageIcon;
import static parques_juego.Parques.amarilla1;
import static parques_juego.Parques.amarilla2;
import static parques_juego.Parques.azul1;
import static parques_juego.Parques.azul2;
import static parques_juego.Parques.roja1;
import static parques_juego.Parques.roja2;
import static parques_juego.Parques.tablero;
import static parques_juego.Parques.verde1;
import static parques_juego.Parques.verde2;

/**
 *
 * @author Angie
 */
public class Parques extends javax.swing.JFrame {

    /**
     * Creates new form Parquest
     */
    public Parques() {
        initComponents();   configComponents();
    }

    //imagen del parques
    public void configComponents() {
        ImageIcon parques = new ImageIcon(getClass().getResource("/images/parques.JPG"));
        ImageIcon icon = new ImageIcon(parques.getImage().getScaledInstance(580, 580, Image.SCALE_DEFAULT));
        tablero.setIcon(icon);

    }

    //funcion para mover las fichas
    public static void moverFichas() {
        if (Dados.cont == 1) {
            if (Dados.num1 == Dados.num2) {
                roja1.setLocation(195, 155);
                roja2.setLocation(220, 155);
            }
        }
        if (Dados.cont == 2) {
            if (Dados.num1 == Dados.num2) {
                verde1.setLocation(465, 240);
                verde2.setLocation(465, 265);
            }
        }
        if (Dados.cont == 3) {
            if (Dados.num1 == Dados.num2) {
                azul1.setLocation(355, 510);
                azul2.setLocation(380, 510);
            }
        }
        if (Dados.cont == 4) {
            if (Dados.num1 == Dados.num2) {
                amarilla1.setLocation(110, 400);
                amarilla2.setLocation(110, 425);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tablero = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        botondados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));
        jPanel1.setLayout(null);

        verde1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fichaverde.png"))); // NOI18N
        jPanel1.add(verde1);
        verde1.setBounds(540, 90, 25, 20);

        verde2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fichaverde.png"))); // NOI18N
        jPanel1.add(verde2);
        verde2.setBounds(460, 160, 25, 20);

        amarilla1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fichaamarilla.png"))); // NOI18N
        jPanel1.add(amarilla1);
        amarilla1.setBounds(120, 580, 25, 20);

        amarilla2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fichaamarilla.png"))); // NOI18N
        jPanel1.add(amarilla2);
        amarilla2.setBounds(40, 500, 25, 20);

        azul1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fichaazul.png"))); // NOI18N
        jPanel1.add(azul1);
        azul1.setBounds(540, 510, 25, 20);

        azul2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fichaazul.png"))); // NOI18N
        jPanel1.add(azul2);
        azul2.setBounds(470, 590, 25, 20);

        roja1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ficharoja.png"))); // NOI18N
        jPanel1.add(roja1);
        roja1.setBounds(120, 170, 30, 20);

        roja2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ficharoja.png"))); // NOI18N
        jPanel1.add(roja2);
        roja2.setBounds(40, 90, 25, 20);

        tablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/parques.JPG"))); // NOI18N
        jPanel1.add(tablero);
        tablero.setBounds(8, 50, 580, 580);

        titulo.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(102, 0, 102));
        titulo.setText("PARQUÉS");
        jPanel1.add(titulo);
        titulo.setBounds(238, 0, 139, 44);

        botondados.setText("LANZAR DADOS");
        botondados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botondadosActionPerformed(evt);
            }
        });
        jPanel1.add(botondados);
        botondados.setBounds(237, 636, 130, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botondadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botondadosActionPerformed
        new Dados().setVisible(true);
    }//GEN-LAST:event_botondadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parques().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JLabel amarilla1 = new javax.swing.JLabel();
    public static final javax.swing.JLabel amarilla2 = new javax.swing.JLabel();
    public static final javax.swing.JLabel azul1 = new javax.swing.JLabel();
    public static final javax.swing.JLabel azul2 = new javax.swing.JLabel();
    private javax.swing.JButton botondados;
    private javax.swing.JPanel jPanel1;
    public static final javax.swing.JLabel roja1 = new javax.swing.JLabel();
    public static final javax.swing.JLabel roja2 = new javax.swing.JLabel();
    public static javax.swing.JLabel tablero;
    private javax.swing.JLabel titulo;
    public static final javax.swing.JLabel verde1 = new javax.swing.JLabel();
    public static final javax.swing.JLabel verde2 = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
