/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parques_juego;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import parques_juego.Jugador;
import parques_juego.AgregarUsuario;

/**
 *
 * @author Pavilion 15
 */
public class Usuarios extends javax.swing.JFrame {

    

    /**
     * Creates new form Usuarios
     */
    AgregarUsuario u = new AgregarUsuario();
    public Usuarios() {
        initComponents();
        configComponents();
        configComponents1();
        configComponents2();
        configFondo();
    }
    
    public void configFondo() {
        ImageIcon fondo = new ImageIcon(getClass().getResource("/images/wallpaper.jpg"));
        ImageIcon icon = new ImageIcon(fondo.getImage().getScaledInstance(labelfondo.getWidth(), labelfondo.getHeight(), Image.SCALE_DEFAULT));
        labelfondo.setIcon(icon);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuarios Registrados");
        setBackground(new java.awt.Color(153, 153, 255));
        setMaximumSize(new java.awt.Dimension(650, 630));
        setMinimumSize(new java.awt.Dimension(650, 630));
        setPreferredSize(new java.awt.Dimension(650, 630));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 57, 607, 123);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 224, 607, 137);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 412, 607, 138);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Categoria Infantil");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 30, 84, 14);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Categoria Juvenil");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 190, 83, 14);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Categoria Mayores");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 380, 91, 14);

        labelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallpaper.jpg"))); // NOI18N
        getContentPane().add(labelfondo);
        labelfondo.setBounds(0, 0, 630, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel labelfondo;
    // End of variables declaration//GEN-END:variables
    //metodo para agregar el contenido a la tabla y configurarla.
    private void configComponents() {
        DefaultTableModel table_model_personas = new DefaultTableModel();
        table_model_personas.addColumn("Id");
        table_model_personas.addColumn("Foto");
        table_model_personas.addColumn("Cedula");
        table_model_personas.addColumn("Nombre");
        table_model_personas.addColumn("Apellido");
        table_model_personas.addColumn("Edad");
        table_model_personas.addColumn("FechaNacimiento");
        table_model_personas.addColumn("FechaResgistro");

        
       
        
        jTable1.setModel(table_model_personas);
        
        u.setTableModel(table_model_personas);
        u.refreshTableModel();
    }
     //metodo para agregar el contenido a la tabla y configurarla.
    private void configComponents1() {
        DefaultTableModel table_model_personas1 = new DefaultTableModel();
        table_model_personas1.addColumn("Id");
        table_model_personas1.addColumn("Foto");
        table_model_personas1.addColumn("Cedula");
        table_model_personas1.addColumn("Nombre");
        table_model_personas1.addColumn("Apellido");
        table_model_personas1.addColumn("Edad");
        table_model_personas1.addColumn("FechaNacimiento");
        table_model_personas1.addColumn("FechaResgistro");

        
        
        jTable2.setModel(table_model_personas1);
        
        u.setTableModel1(table_model_personas1);
        u.refreshTableModel1();
    }
     //metodo para agregar el contenido a la tabla y configurar sus componentes.
    private void configComponents2() {
        DefaultTableModel table_model_personas2 = new DefaultTableModel();
        table_model_personas2.addColumn("Id");
        table_model_personas2.addColumn("Foto");
        table_model_personas2.addColumn("Cedula");
        table_model_personas2.addColumn("Nombre");
        table_model_personas2.addColumn("Apellido");
        table_model_personas2.addColumn("Edad");
        table_model_personas2.addColumn("FechaNacimiento");
        table_model_personas2.addColumn("FechaResgistro");

       
        
        jTable3.setModel(table_model_personas2);
        
        u.setTableModel2(table_model_personas2);
        u.refreshTableModel2();
    }
}
